version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT}:8000"
        volumes:
            - .:/app
        environment:
            - PORT=${PORT}
