[tool.poetry]
name = "cli"
packages = [
  { include = "cli", from = "." }
]

[tool.poetry.dependencies]
click = "^8.1.8"
setuptools = "^78.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
